%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# Optional session saving
# System.LoadAtlasFromFile: "Session_RealSense_Mono"
# System.SaveAtlasToFile: "Session_RealSense_Mono"

#--------------------------------------------------------------------------------------------
# Camera Parameters (OpenCV-style)
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

loopClosing: 1

Camera1.fx: 1696.802685832259
Camera1.fy: 1696.802685832259
Camera1.cx: 960.5
Camera1.cy: 540.5

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

Camera.width: 1920
Camera.height: 1080

Camera.newWidth: 640
Camera.newHeight: 480

Camera.fps: 30

Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters (can be adjusted)
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 1
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

